# Generated by Django 3.1.3 on 2023-02-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230208_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='lession',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='chocies',
            new_name='choices',
        ),
    ]
